build:
  version: "3.1"
spring:
  config:
    import: "configserver:http://configserver:8071/"

accounts:
  message: "Welcome to EazyBank cards related Production APIs "
  contactDetails:
    name: "Smith Ray - Product Owner"
    email: "smithray@eazybank.com"
  onCallSupport:
    - (666) 655-1234
    - (666) 623-1345


management:
  endpoints:
    web:
      exposure:
        include: "health,info"
