
spring:
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "gatewayServer"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"




